INSERT INTO "iva" VALUES(1,'4','ALIQUOTA 4%');
INSERT INTO "iva" VALUES(2,'10','ALIQUOTA 10%');
INSERT INTO "iva" VALUES(3,'20','ALIQUOTA 20%');
INSERT INTO "iva" VALUES(4,'22','ALIQUOTA 22%');
INSERT INTO "iva" VALUES(5,'FC','FUORI CAMPO IVA');